<h3>Login</h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li><a href="<?php echo $this->url('zfcuser'); ?>">Your details</a></li>
  <li class="active">Change Email Address</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left"><?php echo $this->translate('Change Email Address'); ?></h4>
    </div>
    <div class="panel-body">
        <?php
            $form = $this->changeEmailForm;
            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/changeemail'));
            $form->setAttribute('method', 'post');
            $form->get('identity')->setAttribute('class', 'form-control');
            $form->get('newIdentity')->setAttribute('class', 'form-control');
            $form->get('newIdentityVerify')->setAttribute('class', 'form-control');
            $form->get('credential')->setAttribute('class', 'form-control');
            $submitElement = new Zend\Form\Element\Button('submit');
            $submitElement->setLabel('Sign In')
                          ->setAttributes(array(
                              'type'  => 'submit',
                              'class' => 'btn btn-primary'
                          ));
            $form->add($submitElement);
            echo $this->renderForm($form);
        ?>
    </div>
</div>