<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li><a href="<?php echo $this->url('zfcuser'); ?>">Your details</a></li>
  <li class="active">Change Password</li>
</ol>

<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left"><?php echo $this->translate('Change Email Address'); ?></h4>
    </div>
    <div class="panel-body">
        <?php
            $form = $this->changePasswordForm;
            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/changepassword'));
            $form->setAttribute('method', 'post');
        
            $emailElement = $form->get('identity');
            $emailElement->setValue($this->zfcUserIdentity()->getEmail());
            $form->get('identity')->setAttribute('class', 'form-control');
            $form->get('credential')->setAttribute('class', 'form-control');
            $form->get('newCredential')->setAttribute('class', 'form-control');
            $form->get('newCredentialVerify')->setAttribute('class', 'form-control');
            $form->get('submit')->setAttribute('class', 'btn btn-primary');
            echo $this->renderForm($form);
        ?>
    </div>
</div>